#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  +------------------------------------------------+
#  | Title       : ldif2rec                         |
#  | Description : Converts LDIF to recutils format |
#  | Author      : Sven Wick <sven.wick@gmx.de>     |
#  +------------------------------------------------+

import sys
import re
import argparse
from base64 import b64decode

if __name__ == '__main__':

  if sys.stdin.isatty():

    parser = argparse.ArgumentParser(description='Converts LDIF format to recutils format')
    parser.add_argument('file', metavar='FILE', help='file to read, if empty, stdin is used')

    args = parser.parse_args()

    if args.file:
      f = open(args.file)

  else:

    f = sys.stdin

  data = f.read()

  #
  # sanitize file
  #

  #
  # join multiple lines and strip \r
  #
  # e.g.
  #
  # sambaPasswordHistory: 000000000000000000000000000000000000000000000000000000
  #  0000000000
  #
  # gets converted to:
  #
  # sambaPasswordHistory: 0000000000000000000000000000000000000000000000000000000000000000
  #
  # or
  #
  # o:: SU1EIEluc3RpdHV0IGbDvHIgTWVkaXppbmlzY2hlIERpYWdub3N0aWsgQmVybGluLVBvdHNk
  #  YW0gR2JSIElNRCBCZXJsaW4gTVZaIC8gQUNDMiAvICAxODI=
  #
  # becomes
  #
  # o:: SU1EIEluc3RpdHV0IGbDvHIgTWVkaXppbmlzY2hlIERpYWdub3N0aWsgQmVybGluLVBvdHNkYW0gR2JSIElNRCBCZXJsaW4gTVZaIC8gQUNDMiAvICAxODI=
  #
  # so it can be properly base64_decoded
  #

  f = data.replace("\r", "").replace("\n ", "")

  for line in f.split("\n"):

    #
    # find lines with normal data
    #

    match = re.search(r"^([a-zA-Z%][a-zA-Z0-9_]*):\s(.*)", line)

    if match:
      key = match.group(1)
      value = match.group(2)
      print "%s: %s" % ( key, value )
      continue

    #
    # find base64 encoded data and base64_decode it (double colon indicates base64)
    #
    # e.g.
    #
    # sn:: QsO2aG1l
    #
    # gets decoded to:
    #
    # sn: Böhme

    match = re.search(r"^([a-zA-Z%][a-zA-Z0-9_]*)::\s(.*)", line)

    if match:
      key = match.group(1)
      value = b64decode(match.group(2)).replace("\n", "\n+ ") # replace newlines in values with "+ "
                                                              # https://www.gnu.org/software/recutils/manual/recutils.html#Fields
      print "%s: %s" % ( key, value )
      continue

    #
    # output any other line like comments etc...
    #

    print line
