#!/usr/bin/env bash

counter=1

while read line; do

  printf "%2i  %s\n" "$counter" "$line"
  ((counter++))

done < <(ssh -v -o BatchMode=yes ForceLogin2Fail@$1 2>&1 | awk '/Authenticating to/ { print $4 }')
